### ISSUE TITLE
Trouble running `make` on OS X

### ISSUE THREAD

**Issue by mfilej** [lfex/lsci#40]
I'm having trouble running the `make` step on OS X 10.11.3.

The error is the following:
```
$ make
make
Getting dependencies ...
==> lfe (get-deps)
==> ltest (get-deps)
==> lutil (get-deps)
==> kla (get-deps)
==> erlport (get-deps)
Uncaught error in rebar_core: {'EXIT',
                               {function_clause,
                                [{code,which,
                                  [{'lfe-compile',".*",
                                    {git,
                                     "https://github.com/lfe-rebar3/compile.git",
                                     {tag,"0.2.1"}}}],
                                  [{file,"code.erl"},{line,412}]},
                                 {rebar_core,'-plugin_modules/3-lc$^0/1-0-',
                                  1,
                                  [{file,"src/rebar_core.erl"},{line,573}]},
                                 {rebar_core,plugin_modules,3,
                                  [{file,"src/rebar_core.erl"},{line,573}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,244}]},
                                 {rebar_core,process_each,5,
                                  [{file,"src/rebar_core.erl"},{line,351}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,253}]},
                                 {rebar_core,process_each,5,
                                  [{file,"src/rebar_core.erl"},{line,351}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,253}]}]}}
make: *** [get-deps] Error 1
```

I think I have all the dependencies:
```
$ which lfe
/usr/local/bin/lfe
$ lfetool -v
1.4.0
$ python --version
Python 3.5.1
```

I'm not sure what the error means, is there a `lfe-compile` that is missing?

**Comment by oubiwann** [comment]
Oh, dear -- the reason for this is that the lsci ``rebar.config`` project didn't pin its versions ... it uses master :-/ So when some of the other dependencies got updated to use rebar3 (which requires an incompatible ``rebar.config`` file), lsci pulled in the new versions.

I'll update lsci to be rebar3 compatible. It's also been on my list to tackle some more basic features (e.g., better NumPy data type support) ... I should give this some time this weekend.

**Comment by mfilej** [comment]
Ok, thanks for the clear explanation and quick reply!

**Comment by oubiwann** [comment]
Alright, the LFE py project is updated to use pinned versions in its ``rebar.config`` file. Next up, I'll update lsci and test it. Should be close now ...

**Comment by oubiwann** [comment]
Tasks needed in order to fix this:

* [ ] Update lsci to use LFE py 0.0.4
* [ ] Add missing ``lfe.config``

**Comment by oubiwann** [comment]
Okay, I've updated both LFE py and lsci to use pre-rebar3 configurations and dependencies (I'll be updating them both to use rebar3 later).

I've also found and fixed a few minor bugs in lsci. Did a quick test on my Ubuntu machine, and the basics are working now. Let me know how it works for you ...

**Comment by mfilej** [comment]
It works!

I had to remove the `deps` directory before running `make`, after that it ran without any issue.

Thank you so much! :sparkling_heart:
